/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iperc20MetadataSol from "./IPERC20Metadata.sol";
export type { iperc20MetadataSol };
export type { IPERC20 } from "./IPERC20";
export type { PERC20 } from "./PERC20";
export type { PERC20Sample } from "./PERC20Sample";
export * as factories from "./factories";
export { IPERC20__factory } from "./factories/IPERC20__factory";
export type { IERC20Metadata } from "./IPERC20Metadata.sol/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/IPERC20Metadata.sol/IERC20Metadata__factory";
export { PERC20__factory } from "./factories/PERC20__factory";
export { PERC20Sample__factory } from "./factories/PERC20Sample__factory";
